### ISSUE TITLE
gotoX and gotoY

### ISSUE THREAD

**Issue by CylonicRaider** [Kaliom/Petri#2]
The variables `gotoX` and `gotoY` in `petri.js` (lines 36 and 37) are misleadingly named, letting think of abslute movements. Should be rather something like `moveX`, or `dispX`, or something like that.

**Comment by Kaliom** [comment]
Noted, and will be changed in the future :D.

**Comment by Kaliom** [comment]
My local version has been updated, It will be in my next commit :D.
